#!/bin/bash
SUPABASE_URL="https://vvtgpztnytpxoacoflas.supabase.co"
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dGdwenRueXRweG9hY29mbGFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDI5MjQ1MSwiZXhwIjoyMDg5ODY4NDUxfQ.fSncV16A130oJzpP3FViH4qX6loLuukOVK3VfAISAHM"

echo "🌱 Importando 20 recetas más..."

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Bowl yogur frutos rojos","description":"Desayuno antioxidante","prep_time_minutes":5,"calories":280,"protein_g":15,"carbs_g":35,"fat_g":6,"servings":1,"supermarket":"lidl","ingredients":"[{\"item\":\"Yogur griego\",\"amount\":\"200g\"},{\"item\":\"Frutos rojos\",\"amount\":\"100g\"}]","instructions":"[\"Pon yogur\",\"Añade frutos\",\"Espolvorea granola\"]","tags":"[\"desayuno\",\"ligero\"]"}' > /dev/null && echo "✅ Bowl yogur"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Tortitas avena","description":"Desayuno dulce","prep_time_minutes":15,"calories":380,"protein_g":14,"carbs_g":52,"fat_g":12,"servings":2,"supermarket":"mercadona","ingredients":"[{\"item\":\"Avena\",\"amount\":\"80g\"},{\"item\":\"Plátano\",\"amount\":\"2 ud\"}]","instructions":"[\"Tritura avena\",\"Mezcla\",\"Cuaja en sartén\"]","tags":"[\"desayuno\",\"dulce\"]"}' > /dev/null && echo "✅ Tortitas avena"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Huevos espinacas","description":"Desayuno keto","prep_time_minutes":10,"calories":320,"protein_g":22,"carbs_g":6,"fat_g":24,"servings":1,"supermarket":"mercadona","ingredients":"[{\"item\":\"Huevos\",\"amount\":\"3 ud\"},{\"item\":\"Espinacas\",\"amount\":\"50g\"}]","instructions":"[\"Saltea espinacas\",\"Añade huevos\"]","tags":"[\"desayuno\",\"keto\"]"}' > /dev/null && echo "✅ Huevos espinacas"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Pasta pavo","description":"Comida completa","prep_time_minutes":20,"calories":550,"protein_g":38,"carbs_g":62,"fat_g":14,"servings":1,"supermarket":"lidl","ingredients":"[{\"item\":\"Pasta integral\",\"amount\":\"100g\"},{\"item\":\"Pavo\",\"amount\":\"150g\"}]","instructions":"[\"Cuece pasta\",\"Saltea pavo\",\"Mezcla\"]","tags":"[\"comida\",\"pasta\"]"}' > /dev/null && echo "✅ Pasta pavo"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Lentejas verduras","description":"Comida con hierro","prep_time_minutes":45,"calories":420,"protein_g":22,"carbs_g":58,"fat_g":8,"servings":2,"supermarket":"mercadona","ingredients":"[{\"item\":\"Lentejas\",\"amount\":\"200g\"},{\"item\":\"Zanahoria\",\"amount\":\"2 ud\"}]","instructions":"[\"Remoja noche\",\"Sofríe\",\"Cuece 40min\"]","tags":"[\"comida\",\"legumbres\"]"}' > /dev/null && echo "✅ Lentejas"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Wrap pollo","description":"Comida portátil","prep_time_minutes":15,"calories":380,"protein_g":32,"carbs_g":28,"fat_g":14,"servings":1,"supermarket":"mercadona","ingredients":"[{\"item\":\"Tortilla trigo\",\"amount\":\"1 ud\"},{\"item\":\"Pollo\",\"amount\":\"120g\"}]","instructions":"[\"Corta pollo\",\"Calienta tortilla\",\"Enrolla\"]","tags":"[\"comida\",\"portátil\"]"}' > /dev/null && echo "✅ Wrap pollo"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Arroz verduras","description":"Comida vegana","prep_time_minutes":30,"calories":420,"protein_g":12,"carbs_g":78,"fat_g":8,"servings":1,"supermarket":"aldi","ingredients":"[{\"item\":\"Arroz integral\",\"amount\":\"100g\"},{\"item\":\"Pimiento\",\"amount\":\"1 ud\"}]","instructions":"[\"Cuece arroz\",\"Saltea verduras\"]","tags":"[\"comida\",\"vegano\"]"}' > /dev/null && echo "✅ Arroz verduras"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Pavo horno","description":"Comida tradicional","prep_time_minutes":40,"calories":480,"protein_g":42,"carbs_g":45,"fat_g":12,"servings":2,"supermarket":"mercadona","ingredients":"[{\"item\":\"Pavo\",\"amount\":\"300g\"},{\"item\":\"Patatas\",\"amount\":\"300g\"}]","instructions":"[\"Horno 180°C","Hornear 35min"]","tags":"[\"comida\",\"horno\"]"}' > /dev/null && echo "✅ Pavo horno"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Ensalada César","description":"Comida clásica","prep_time_minutes":20,"calories":450,"protein_g":35,"carbs_g":22,"fat_g":24,"servings":1,"supermarket":"lidl","ingredients":"[{\"item\":\"Lechuga\",\"amount\":\"150g\"},{\"item\":\"Pollo\",\"amount\":\"150g\"}]","instructions":"[\"Corta lechuga\",\"Cocina pollo\",\"Mezcla\"]","tags":"[\"comida\",\"ensalada\"]"}' > /dev/null && echo "✅ Ensalada César"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Merluza vapor","description":"Cena ligera","prep_time_minutes":25,"calories":340,"protein_g":32,"carbs_g":38,"fat_g":4,"servings":1,"supermarket":"lidl","ingredients":"[{\"item\":\"Merluza\",\"amount\":\"180g\"},{\"item\":\"Patatas\",\"amount\":\"200g\"}]","instructions":"[\"Vaporera 20min"]","tags":"[\"cena\",\"pescado\"]"}' > /dev/null && echo "✅ Merluza vapor"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Gambas ajillo","description":"Cena rápida","prep_time_minutes":10,"calories":220,"protein_g":24,"carbs_g":4,"fat_g":12,"servings":1,"supermarket":"mercadona","ingredients":"[{\"item\":\"Gambas\",\"amount\":\"200g\"},{\"item\":\"Ajo\",\"amount\":\"4 dientes\"}]","instructions":"[\"Saltea 2-3min"]","tags":"[\"cena\",\"marisco\"]"}' > /dev/null && echo "✅ Gambas ajillo"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Tofu verduras","description":"Cena vegana","prep_time_minutes":20,"calories":320,"protein_g":22,"carbs_g":18,"fat_g":18,"servings":1,"supermarket":"lidl","ingredients":"[{\"item\":\"Tofu\",\"amount\":\"200g\"},{\"item\":\"Brócoli\",\"amount\":\"150g\"}]","instructions":"[\"Saltea tofu\",\"Añade verduras\"]","tags":"[\"cena\",\"vegano\"]"}' > /dev/null && echo "✅ Tofu verduras"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Champiñones revuelto","description":"Cena keto","prep_time_minutes":12,"calories":240,"protein_g":18,"carbs_g":6,"fat_g":16,"servings":1,"supermarket":"aldi","ingredients":"[{\"item\":\"Huevos\",\"amount\":\"2 ud\"},{\"item\":\"Champiñones\",\"amount\":\"150g\"}]","instructions":"[\"Saltea champiñones\",\"Añade huevos\"]","tags":"[\"cena\",\"keto\"]"}' > /dev/null && echo "✅ Champiñones"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Huevos rellenos","description":"Cena creativa","prep_time_minutes":20,"calories":320,"protein_g":26,"carbs_g":6,"fat_g":22,"servings":2,"supermarket":"mercadona","ingredients":"[{\"item\":\"Huevos\",\"amount\":\"4 ud\"},{\"item\":\"Atún\",\"amount\":\"2 latas\"}]","instructions":"[\"Cuece huevos\",\"Rellena"]","tags":"[\"cena\",\"huevos\"]"}' > /dev/null && echo "✅ Huevos rellenos"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Batido proteína","description":"Snack post-entreno","prep_time_minutes":5,"calories":280,"protein_g":25,"carbs_g":32,"fat_g":4,"servings":1,"supermarket":"familycash","ingredients":"[{\"item\":\"Proteína\",\"amount\":\"30g\"},{\"item\":\"Plátano\",\"amount\":\"1 ud\"}]","instructions":"[\"Tritura todo\"]","tags":"[\"snack\",\"proteico\"]"}' > /dev/null && echo "✅ Batido proteína"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Yogur nueces","description":"Snack saludable","prep_time_minutes":3,"calories":220,"protein_g":12,"carbs_g":24,"fat_g":10,"servings":1,"supermarket":"mercadona","ingredients":"[{\"item\":\"Yogur griego\",\"amount\":\"150g\"},{\"item\":\"Nueces\",\"amount\":\"30g\"}]","instructions":"[\"Mezcla todo\"]","tags":"[\"snack\",\"saludable\"]"}' > /dev/null && echo "✅ Yogur nueces"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Zanahoria hummus","description":"Snack crujiente","prep_time_minutes":5,"calories":180,"protein_g":8,"carbs_g":22,"fat_g":6,"servings":1,"supermarket":"aldi","ingredients":"[{\"item\":\"Zanahoria\",\"amount\":\"2 ud\"},{\"item\":\"Hummus\",\"amount\":\"100g\"}]","instructions":"[\"Corta zanahoria\",\"Sirve hummus\"]","tags":"[\"snack\",\"vegano\"]"}' > /dev/null && echo "✅ Zanahoria hummus"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Tostada tomate","description":"Snack ligero","prep_time_minutes":5,"calories":150,"protein_g":6,"carbs_g":28,"fat_g":2,"servings":1,"supermarket":"mercadona","ingredients":"[{\"item\":\"Pan integral\",\"amount\":\"2 rebanadas\"},{\"item\":\"Tomate\",\"amount\":\"2 ud\"}]","instructions":"[\"Tuesta pan\",\"Ralla tomate\"]","tags":"[\"snack\",\"ligero\"]"}' > /dev/null && echo "✅ Tostada tomate"

curl -s -X POST "$SUPABASE_URL/rest/v1/recipes" -H "apikey: $SERVICE_KEY" -H "Authorization: Bearer $SERVICE_KEY" -H "Content-Type: application/json" -d '{"name":"Almendras","description":"Snack energético","prep_time_minutes":1,"calories":200,"protein_g":8,"carbs_g":8,"fat_g":18,"servings":1,"supermarket":"familycash","ingredients":"[{\"item\":\"Almendras\",\"amount\":\"30g\"}]","instructions":"[\"Come directamente\"]","tags":"[\"snack\",\"energia\"]"}' > /dev/null && echo "✅ Almendras"

echo ""
echo "✅ 20 recetas adicionales importadas"
echo "📊 Total: 25 recetas en DB"
